languageCode = "en"
languageName = "English"
weight = 1

title = "Daniel-Andrei Minca"
# logo = "img/logo.jpg"
#copyright = "CC BY-NC"


[params.author]
  name = "Daniel-Andrei Minca"
  #image = "img/author.jpg"
  headline = "Site Reliability Engineer"
  bio = "I understand things by breaking them apart"
  links = [
    { email = "mailto:mallard-broad0q@icloud.com" },
    { github = "https://github.com/dminca" },
    { gitlab = "https://gitlab.com/dminca" },
    { codeberg = "https://codeberg.org/dminca" },
    { linkedin = "https://www.linkedin.com/in/dminca" },
    { xing = "https://www.xing.com/profile/DanielAndrei_Minca" },
    { mastodon = "https://mastodontech.de/@dminca" },
    { pixelfed = "https://pixelfed.social/dminca" },
    { stack-overflow = "https://stackoverflow.com/users/2733115/daniel-andrei-mincă" },
    { telegram = "https://t.me/dminca" },
    { threema = "https://threema.id/T965PNBS" },
    { matrix = "https://matrix.to/#/@dminca:matrix.org" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
